=== cr0xvs/EXAMENT4REPO/EXAMENT4REPO/DTD/Almacen.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT sede (sucursal)>
<!ELEMENT sucursal (lugar,trabajador+)>
<!ELEMENT lugar (#PCDATA)>
<!ATTLIST sucursal codigo CDATA #REQUIRED>
<!ELEMENT trabajador (nombre, fecha, observaciones, articulos+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT articulos (unidades+, precio, observacion, plazo)>
<!ATTLIST articulos codigo CDATA #REQUIRED>
<!ELEMENT unidades (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT observacion (#PCDATA)>
<!ELEMENT plazo (#PCDATA)>

=== cr0xvs/EXAMENT4REPO/EXAMENT4REPO/DTD/Almancen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sede SYSTEM "Almacen.dtd">
<sede>
    <sucursal codigo="A1234567">
        <lugar> Ubrique </lugar>
        <trabajador>
            <nombre> Pepe </nombre>
            <fecha> 05/02/2021 </fecha>
            <observaciones> Urgente </observaciones>
            <articulos codigo="ABC123">
                <unidades> 2000 </unidades>
                <precio> 2500 </precio>
                <observacion> Mascarillas para una farmacia </observacion>
                <plazo> 10 </plazo>
            </articulos>
            <articulos codigo="ABD412">
                <unidades> 2000 </unidades>
                <precio> 2300 </precio>
                <observacion> Gel para desinfectar manos </observacion>
                <plazo> 8 </plazo>
            </articulos>
        </trabajador>
    </sucursal>
</sede>
